#docker compose -f deploy-postgres-zipkin-compose.yml build
#docker compose -f deploy-postgres-zipkin-compose.yml up
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: mini_project_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local