spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RetSokhim/configuration-repo-mini-project
          default-label: main
          timeout: 10000
          clone-on-start: true
server:
  port: 8888